### Data Pre-Processing


1. **Obtaining the data -** data consists of budget text documents in the form of PDF files obtained from the following organizations: 

   * [Guilford County](https://www.guilfordcountync.gov/home/showdocument?id=9497)
   * [Durham County](https://www.dconc.gov/home/showdocument?id=27985)
   * [City of Durham](https://durhamnc.gov/DocumentCenter/View/27412/FY20-Final-Budget)
   * [City of Charlotte](https://charlottenc.gov/budget/FY2020%20Documents/FY%202020%20Adopted%20Budget%20Book%207-31%20Complete.pdf)
   * [Mecklenburg County](https://www.mecknc.gov/CountyManagersOffice/OMB/Documents/FY2020%20Adopted%20Budget.pdf) <br/>
   * [Wake County](http://www.wakegov.com/budget/fy20/Documents/FY20%20Adopted%20Budget%20Book.pdf)
   * [City of Raleigh](https://user-2081353526.cld.bz/FY2020AdoptedBudget)
   
After the PDF files are collected, they are compressed to reduce the size getting them ready to be converted into CSV files using an app developed by project mentor:
           **[Jason Jones](https://www.linkedin.com/in/jones-jason-adam/),**
           **click [here](https://jason-jones.shinyapps.io/Emotionizer/) for the App**
       
2. **Cleaning the data -** performing some popular text pre-processing techniques


3. **Organizing the data -** organizing the cleaned data into a way that is easy to input into other algorithms

### FY2018 Data Preprocessig Starts Here

In [1]:
#Importing packages
import os
import glob
import nltk
import pandas as pd
import numpy as np

In [2]:
# change the current directory to read the data
os.chdir(r"C:\Users\Sultan\Documents\GitHub\Budget_Text_Analysis\util\data\FY2018\structured\original")

### 1- Obtaining the data

#### Reading and labling data for all organizations

In [3]:
# 1- Reading Guilford-County data file 
GC_df = pd.read_csv("GuilfordCountyOriginalDataFY18.csv", engine='python')
# inserting "organization" column with static value 
# corresponding to the organization in question 
GC_df.insert(2, "organization", "Guilford County")


# 2- For Charlotte-City data
CC_df = pd.read_csv(r'CharlotteCityOriginalDataFY18.csv', engine='python')
CC_df.insert(2, "organization", "Charlotte City")

# 3- For Durham-City data
DCity_df = pd.read_csv(r'DurhamCityOriginalDataFY18.csv', engine='python')
DCity_df.insert(2, "organization", "Durham City")

# 4- For Durham-County data
DCounty_df = pd.read_csv(r'DurhamCountyOriginalDataFY18.csv', engine='python')
DCounty_df.insert(2, "organization", "Durham County")

# 5- For Mecklenburg-County data
MC_df = pd.read_csv(r'MecklenburgCountyOriginalDataFY18.csv', engine='python')
MC_df.insert(2, "organization", "Mecklenburg County")

# 6- For Raleigh-City data
RC_df = pd.read_csv(r'RaleighCityOriginalDataFY18.csv', engine='python')
RC_df.insert(2, "organization", "Raleigh City")

# 7- For Wake-County data
WC_df = pd.read_csv(r'WakeCountyOriginalDataFY18.csv', engine='python')
WC_df.insert(2, "organization", "Wake County")

In [4]:
# Combine all dataframes into a single dataframe using concat() function
# Row lables are adjusted automaticlly by passing ignore_index=True
data =  pd.concat([GC_df, CC_df, DCity_df, 
                   DCounty_df, MC_df, RC_df, WC_df], ignore_index=True)
data

        Unnamed: 0  page_number     organization     word
0                1            1  Guilford County       fy
1                2            1  Guilford County  adopted
2                3            1  Guilford County   budget
3                4            1  Guilford County     july
4                5            1  Guilford County     june
...            ...          ...              ...      ...
621551      129788          542      Wake County    index
621552      129789          542      Wake County   fiscal
621553      129790          542      Wake County     year
621554      129791          542      Wake County  adopted
621555      129792          542      Wake County   budget

[621556 rows x 4 columns]

### 2- Cleaning the Data

In [5]:
# listing columns in data frame 
list(data)

['Unnamed: 0', 'page_number', 'organization', 'word']

#### Dropping and reordering columns

In [6]:
# delete columns using the columns parameter of drop
data = data.drop(columns="Unnamed: 0")

# re-order columns
data = data[['page_number','word','organization']]

data.head()

   page_number     word     organization
0            1       fy  Guilford County
1            1  adopted  Guilford County
2            1   budget  Guilford County
3            1     july  Guilford County
4            1     june  Guilford County

#### Adding "Year" column with a static value corresponding to the year in question

In [7]:
data.insert(3, "year", "FY2018")
data.head()

   page_number     word     organization    year
0            1       fy  Guilford County  FY2018
1            1  adopted  Guilford County  FY2018
2            1   budget  Guilford County  FY2018
3            1     july  Guilford County  FY2018
4            1     june  Guilford County  FY2018

####  Text normalization:

* ##### Lowercasing

In [8]:
# using a function to lowercase all text entries in column 'word'
data['word'] = data['word'].apply(lambda x: " ".join(x.lower() 
                                                     for x in x.split()))

data

        page_number     word     organization    year
0                 1       fy  Guilford County  FY2018
1                 1  adopted  Guilford County  FY2018
2                 1   budget  Guilford County  FY2018
3                 1     july  Guilford County  FY2018
4                 1     june  Guilford County  FY2018
...             ...      ...              ...     ...
621551          542    index      Wake County  FY2018
621552          542   fiscal      Wake County  FY2018
621553          542     year      Wake County  FY2018
621554          542  adopted      Wake County  FY2018
621555          542   budget      Wake County  FY2018

[621556 rows x 4 columns]

* ##### Lemmatization

#### Removing stop words

In [9]:
# Load library
from nltk.corpus import stopwords

# Download the set of stop words the first time
nltk.download('stopwords')

# Load stop words
stop_words = stopwords.words('english')

data['word'] = data['word'].apply(lambda x: " ".join(x 
                            for x in x.split() if x not in stop_words))
data.head(50)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sultan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

    page_number        word     organization    year
0             1          fy  Guilford County  FY2018
1             1     adopted  Guilford County  FY2018
2             1      budget  Guilford County  FY2018
3             1        july  Guilford County  FY2018
4             1        june  Guilford County  FY2018
5             1    guilford  Guilford County  FY2018
6             1      county  Guilford County  FY2018
7             1       state  Guilford County  FY2018
8             1              Guilford County  FY2018
9             1       north  Guilford County  FY2018
10            1    carolina  Guilford County  FY2018
11            2              Guilford County  FY2018
12            2              Guilford County  FY2018
13            2    children  Guilford County  FY2018
14            2              Guilford County  FY2018
15            2    guilford  Guilford County  FY2018
16            2      county  Guilford County  FY2018
17            2              Guilford County  FY2018
18            2        ages  Guilford County  FY2018
19            2              Guilford County  FY2018
20            2              Guilford County  FY2018
21            2       every  Guilford County  FY2018
22            2    children  Guilford County  FY2018
23            2        live  Guilford County  FY2018
24            2              Guilford County  FY2018
25            2  households  Guilford County  FY2018
26            2   receiving  Guilford County  FY2018
27            2              Guilford County  FY2018
28            2        form  Guilford County  FY2018
29            2              Guilford County  FY2018
30            2      school  Guilford County  FY2018
31            2        aged  Guilford County  FY2018
32            2              Guilford County  FY2018
33            2      public  Guilford County  FY2018
34            2  assistance  Guilford County  FY2018
35            2              Guilford County  FY2018
36            2    enrolled  Guilford County  FY2018
37            2              Guilford County  FY2018
38            2      school  Guilford County  FY2018
39            2        live  Guilford County  FY2018
40            2              Guilford County  FY2018
41            2  households  Guilford County  FY2018
42            2              Guilford County  FY2018
43            2      income  Guilford County  FY2018
44            2              Guilford County  FY2018
45            2              Guilford County  FY2018
46            2              Guilford County  FY2018
47            2    enrolled  Guilford County  FY2018
48            2              Guilford County  FY2018
49            2      school  Guilford County  FY2018

In [10]:
# Regex with the pattern replacing not alphanumeric/whitespace with a space
data['word'] = data['word'].str.replace('[^\w\s]','')

data.head()

   page_number     word     organization    year
0            1       fy  Guilford County  FY2018
1            1  adopted  Guilford County  FY2018
2            1   budget  Guilford County  FY2018
3            1     july  Guilford County  FY2018
4            1     june  Guilford County  FY2018

In [11]:
# Replacing empty cells with null values, so we can drop all NaN values later
data['word'].replace('', np.nan, inplace=True)

# Drop all NaN values from the data frames
data.dropna(subset=['word'], inplace=True)
data.head()

   page_number     word     organization    year
0            1       fy  Guilford County  FY2018
1            1  adopted  Guilford County  FY2018
2            1   budget  Guilford County  FY2018
3            1     july  Guilford County  FY2018
4            1     june  Guilford County  FY2018

### 2- Organizing the Data

We already created a corpus in an earlier step. The definition of a corpus is a collection of texts, and they are all put together neatly in a pandas dataframe here.

In [12]:
# Let's take a look at our dataframe
data

        page_number     word     organization    year
0                 1       fy  Guilford County  FY2018
1                 1  adopted  Guilford County  FY2018
2                 1   budget  Guilford County  FY2018
3                 1     july  Guilford County  FY2018
4                 1     june  Guilford County  FY2018
...             ...      ...              ...     ...
621551          542    index      Wake County  FY2018
621552          542   fiscal      Wake County  FY2018
621553          542     year      Wake County  FY2018
621554          542  adopted      Wake County  FY2018
621555          542   budget      Wake County  FY2018

[450614 rows x 4 columns]

#### Dataframe to one single and clean csv file

In [13]:
# Export dataframe to csv
data.to_csv(r"C:\Users\Sultan\Documents\GitHub\Budget_Text_Analysis\util\data\PreprocessedOriginalData\PreprocessedOriginalDataFY18.csv", index=False, encoding='utf-8-sig')

In [14]:
# Change the dirctory for pickle file to be stored properly
os.chdir(r"C:\Users\Sultan\Documents\GitHub\Budget_Text_Analysis\util\data\PreprocessedOriginalData\pickle") 
# Let's pickle it for later use
data.to_pickle("DataFY18.pkl")